// Generated by Phaser Editor v1.2.1

/**
 * Scene3.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function Scene3(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	var prefabRoot_Scene1 = this.game.add.group(this);

	var prefabRoot_Scene1 = this.game.add.group(prefabRoot_Scene1);

	var prefabRoot_Scene1 = this.game.add.group(prefabRoot_Scene1);

	var CollisionLayer = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var COB003 = this.game.add.sprite(8128, 576, 'tiles', 'physics', CollisionLayer);
	COB003.scale.setTo(5.12, 5.12);
	COB003.body.immovable = true;
	COB003.body.allowRotation = false;
	COB003.body.allowGravity = false;

	var COB002 = this.game.add.sprite(6144, 576, 'tiles', 'physics', CollisionLayer);
	COB002.scale.setTo(5.12, 5.12);
	COB002.body.immovable = true;
	COB002.body.allowRotation = false;
	COB002.body.allowGravity = false;

	var COB001 = this.game.add.sprite(4288, 640, 'tiles', 'physics', CollisionLayer);
	COB001.scale.setTo(10.48, 2.56);
	COB001.body.immovable = true;
	COB001.body.allowRotation = false;
	COB001.body.allowGravity = false;

	var COB000 = this.game.add.sprite(3712, 576, 'tiles', 'physics', CollisionLayer);
	COB000.scale.setTo(5.12, 5.12);
	COB000.body.immovable = true;
	COB000.body.allowRotation = false;
	COB000.body.allowGravity = false;

	var CGR002C = this.game.add.sprite(8128, 704, 'tiles', 'physics', CollisionLayer);
	CGR002C.scale.setTo(51.2, 2.56);
	CGR002C.body.immovable = true;
	CGR002C.body.allowRotation = false;
	CGR002C.body.allowGravity = false;

	var CGR002B = this.game.add.sprite(6848, 704, 'tiles', 'physics', CollisionLayer);
	CGR002B.scale.setTo(51.2, 2.56);
	CGR002B.body.immovable = true;
	CGR002B.body.allowRotation = false;
	CGR002B.body.allowGravity = false;
	CGR002B.body.friction.x = 0.0;

	var CGR002 = this.game.add.sprite(5568, 704, 'tiles', 'physics', CollisionLayer);
	CGR002.scale.setTo(51.2, 2.56);
	CGR002.body.immovable = true;
	CGR002.body.allowRotation = false;
	CGR002.body.allowGravity = false;

	var CGR001 = this.game.add.sprite(1920, 704, 'tiles', 'physics', CollisionLayer);
	CGR001.scale.setTo(138.24, 2.56);
	CGR001.body.immovable = true;
	CGR001.body.allowRotation = false;
	CGR001.body.allowGravity = false;

	var CGR000 = this.game.add.sprite(0, 704, 'tiles', 'physics', CollisionLayer);
	CGR000.scale.setTo(69.12, 2.56);
	CGR000.body.immovable = true;
	CGR000.body.allowRotation = false;
	CGR000.body.allowGravity = false;

	var Water = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var W006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	this.game.add.tileSprite(5376, 768, 64, 64, 'watersprite1', null, W001);

	this.game.add.tileSprite(5440, 768, 64, 64, 'watersprite1', null, W001);

	this.game.add.tileSprite(5504, 768, 64, 64, 'watersprite1', null, W001);

	var W000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	this.game.add.tileSprite(1728, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(1792, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(1856, 768, 64, 64, 'watersprite1', null, W000);

	var Hazards = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var FIREWALL = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);
	H010.position.setTo(67008, 5376);

	var H00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);
	H00E.position.setTo(0, 512);

	var H00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);
	H00D.position.setTo(89344, 7168);

	var H00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(8064, 576, 64, 64, 'icespikepngleft', null, H002);

	this.game.add.tileSprite(8064, 640, 64, 64, 'icespikepngleft', null, H002);

	var H001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(3072, 640, 64, 64, 'spikepng', null, H001);

	this.game.add.tileSprite(3136, 640, 64, 64, 'spikepng', null, H001);

	this.game.add.tileSprite(3200, 640, 64, 64, 'spikepng', null, H001);

	var H000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var firetilespritesheet4 = this.game.add.sprite(2368, 640, 'firetilespritesheet', 0, H000);
	firetilespritesheet4.animations.add('Fire', [0, 1, 2, 3], 60, false);

	var firetilespritesheet41 = this.game.add.sprite(2432, 640, 'firetilespritesheet', 0, H000);
	firetilespritesheet41.animations.add('Fire', [0, 1, 2, 3], 60, false);

	var GroundBase = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var Ground4 = this.game.add.tileSprite(0, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4.body.immovable = true;
	Ground4.body.allowRotation = false;
	Ground4.body.allowGravity = false;

	var Ground41 = this.game.add.tileSprite(64, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41.body.immovable = true;
	Ground41.body.allowRotation = false;
	Ground41.body.allowGravity = false;

	var Ground42 = this.game.add.tileSprite(128, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground42.body.immovable = true;
	Ground42.body.allowRotation = false;
	Ground42.body.allowGravity = false;

	var Ground43 = this.game.add.tileSprite(192, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground43.body.immovable = true;
	Ground43.body.allowRotation = false;
	Ground43.body.allowGravity = false;

	var Ground44 = this.game.add.tileSprite(256, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground44.body.immovable = true;
	Ground44.body.allowRotation = false;
	Ground44.body.allowGravity = false;

	var Ground45 = this.game.add.tileSprite(320, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground45.body.immovable = true;
	Ground45.body.allowRotation = false;
	Ground45.body.allowGravity = false;

	var Ground46 = this.game.add.tileSprite(384, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground46.body.immovable = true;
	Ground46.body.allowRotation = false;
	Ground46.body.allowGravity = false;

	var Ground47 = this.game.add.tileSprite(448, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground47.body.immovable = true;
	Ground47.body.allowRotation = false;
	Ground47.body.allowGravity = false;

	var Ground48 = this.game.add.tileSprite(512, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground48.body.immovable = true;
	Ground48.body.allowRotation = false;
	Ground48.body.allowGravity = false;

	var Ground49 = this.game.add.tileSprite(576, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground49.body.immovable = true;
	Ground49.body.allowRotation = false;
	Ground49.body.allowGravity = false;

	var Ground410 = this.game.add.tileSprite(640, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground410.body.immovable = true;
	Ground410.body.allowRotation = false;
	Ground410.body.allowGravity = false;

	var Ground411 = this.game.add.tileSprite(704, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground411.body.immovable = true;
	Ground411.body.allowRotation = false;
	Ground411.body.allowGravity = false;

	var Ground412 = this.game.add.tileSprite(768, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground412.body.immovable = true;
	Ground412.body.allowRotation = false;
	Ground412.body.allowGravity = false;

	var Ground413 = this.game.add.tileSprite(832, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground413.body.immovable = true;
	Ground413.body.allowRotation = false;
	Ground413.body.allowGravity = false;

	var Ground414 = this.game.add.tileSprite(896, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground414.body.immovable = true;
	Ground414.body.allowRotation = false;
	Ground414.body.allowGravity = false;

	var Ground415 = this.game.add.tileSprite(960, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground415.body.immovable = true;
	Ground415.body.allowRotation = false;
	Ground415.body.allowGravity = false;

	var Ground416 = this.game.add.tileSprite(1024, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground416.body.immovable = true;
	Ground416.body.allowRotation = false;
	Ground416.body.allowGravity = false;

	var Ground417 = this.game.add.tileSprite(1088, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground417.body.immovable = true;
	Ground417.body.allowRotation = false;
	Ground417.body.allowGravity = false;

	var Ground418 = this.game.add.tileSprite(1152, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground418.body.immovable = true;
	Ground418.body.allowRotation = false;
	Ground418.body.allowGravity = false;

	var Ground419 = this.game.add.tileSprite(1216, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground419.body.immovable = true;
	Ground419.body.allowRotation = false;
	Ground419.body.allowGravity = false;

	var Ground4131 = this.game.add.tileSprite(1280, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4131.body.immovable = true;
	Ground4131.body.allowRotation = false;
	Ground4131.body.allowGravity = false;

	var Ground4141 = this.game.add.tileSprite(1344, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4141.body.immovable = true;
	Ground4141.body.allowRotation = false;
	Ground4141.body.allowGravity = false;

	var Ground4151 = this.game.add.tileSprite(1408, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4151.body.immovable = true;
	Ground4151.body.allowRotation = false;
	Ground4151.body.allowGravity = false;

	var Ground4161 = this.game.add.tileSprite(1472, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4161.body.immovable = true;
	Ground4161.body.allowRotation = false;
	Ground4161.body.allowGravity = false;

	var Ground4171 = this.game.add.tileSprite(1536, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4171.body.immovable = true;
	Ground4171.body.allowRotation = false;
	Ground4171.body.allowGravity = false;

	var Ground4181 = this.game.add.tileSprite(1600, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4181.body.immovable = true;
	Ground4181.body.allowRotation = false;
	Ground4181.body.allowGravity = false;

	var Ground4191 = this.game.add.tileSprite(1664, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4191.body.immovable = true;
	Ground4191.body.allowRotation = false;
	Ground4191.body.allowGravity = false;

	var Ground420 = this.game.add.tileSprite(1920, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground420.body.immovable = true;
	Ground420.body.allowRotation = false;
	Ground420.body.allowGravity = false;

	var Ground4110 = this.game.add.tileSprite(1984, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4110.body.immovable = true;
	Ground4110.body.allowRotation = false;
	Ground4110.body.allowGravity = false;

	var Ground421 = this.game.add.tileSprite(2048, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground421.body.immovable = true;
	Ground421.body.allowRotation = false;
	Ground421.body.allowGravity = false;

	var Ground431 = this.game.add.tileSprite(2112, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground431.body.immovable = true;
	Ground431.body.allowRotation = false;
	Ground431.body.allowGravity = false;

	var Ground441 = this.game.add.tileSprite(2176, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground441.body.immovable = true;
	Ground441.body.allowRotation = false;
	Ground441.body.allowGravity = false;

	var Ground451 = this.game.add.tileSprite(2240, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground451.body.immovable = true;
	Ground451.body.allowRotation = false;
	Ground451.body.allowGravity = false;

	var Ground461 = this.game.add.tileSprite(2304, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground461.body.immovable = true;
	Ground461.body.allowRotation = false;
	Ground461.body.allowGravity = false;

	var Ground471 = this.game.add.tileSprite(2368, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground471.body.immovable = true;
	Ground471.body.allowRotation = false;
	Ground471.body.allowGravity = false;

	var Ground481 = this.game.add.tileSprite(2432, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground481.body.immovable = true;
	Ground481.body.allowRotation = false;
	Ground481.body.allowGravity = false;

	var Ground491 = this.game.add.tileSprite(2496, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground491.body.immovable = true;
	Ground491.body.allowRotation = false;
	Ground491.body.allowGravity = false;

	var Ground4101 = this.game.add.tileSprite(2560, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4101.body.immovable = true;
	Ground4101.body.allowRotation = false;
	Ground4101.body.allowGravity = false;

	var Ground4111 = this.game.add.tileSprite(2624, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4111.body.immovable = true;
	Ground4111.body.allowRotation = false;
	Ground4111.body.allowGravity = false;

	var Ground4121 = this.game.add.tileSprite(2688, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4121.body.immovable = true;
	Ground4121.body.allowRotation = false;
	Ground4121.body.allowGravity = false;

	var Ground4132 = this.game.add.tileSprite(2752, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4132.body.immovable = true;
	Ground4132.body.allowRotation = false;
	Ground4132.body.allowGravity = false;

	var Ground4142 = this.game.add.tileSprite(2816, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4142.body.immovable = true;
	Ground4142.body.allowRotation = false;
	Ground4142.body.allowGravity = false;

	var Ground4152 = this.game.add.tileSprite(2880, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4152.body.immovable = true;
	Ground4152.body.allowRotation = false;
	Ground4152.body.allowGravity = false;

	var Ground4162 = this.game.add.tileSprite(2944, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4162.body.immovable = true;
	Ground4162.body.allowRotation = false;
	Ground4162.body.allowGravity = false;

	var Ground4172 = this.game.add.tileSprite(3008, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4172.body.immovable = true;
	Ground4172.body.allowRotation = false;
	Ground4172.body.allowGravity = false;

	var Ground4182 = this.game.add.tileSprite(3072, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4182.body.immovable = true;
	Ground4182.body.allowRotation = false;
	Ground4182.body.allowGravity = false;

	var Ground4192 = this.game.add.tileSprite(3136, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4192.body.immovable = true;
	Ground4192.body.allowRotation = false;
	Ground4192.body.allowGravity = false;

	var Ground41311 = this.game.add.tileSprite(3200, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41311.body.immovable = true;
	Ground41311.body.allowRotation = false;
	Ground41311.body.allowGravity = false;

	var Ground41411 = this.game.add.tileSprite(3264, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41411.body.immovable = true;
	Ground41411.body.allowRotation = false;
	Ground41411.body.allowGravity = false;

	var Ground41511 = this.game.add.tileSprite(3328, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41511.body.immovable = true;
	Ground41511.body.allowRotation = false;
	Ground41511.body.allowGravity = false;

	var Ground41611 = this.game.add.tileSprite(3392, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41611.body.immovable = true;
	Ground41611.body.allowRotation = false;
	Ground41611.body.allowGravity = false;

	var Ground41711 = this.game.add.tileSprite(3456, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41711.body.immovable = true;
	Ground41711.body.allowRotation = false;
	Ground41711.body.allowGravity = false;

	var Ground41811 = this.game.add.tileSprite(3520, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41811.body.immovable = true;
	Ground41811.body.allowRotation = false;
	Ground41811.body.allowGravity = false;

	var Ground41911 = this.game.add.tileSprite(3584, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41911.body.immovable = true;
	Ground41911.body.allowRotation = false;
	Ground41911.body.allowGravity = false;

	var Ground422 = this.game.add.tileSprite(3648, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground422.body.immovable = true;
	Ground422.body.allowRotation = false;
	Ground422.body.allowGravity = false;

	var Ground4112 = this.game.add.tileSprite(3712, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4112.body.immovable = true;
	Ground4112.body.allowRotation = false;
	Ground4112.body.allowGravity = false;

	var Ground423 = this.game.add.tileSprite(3776, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground423.body.immovable = true;
	Ground423.body.allowRotation = false;
	Ground423.body.allowGravity = false;

	var Ground432 = this.game.add.tileSprite(3840, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground432.body.immovable = true;
	Ground432.body.allowRotation = false;
	Ground432.body.allowGravity = false;

	var Ground442 = this.game.add.tileSprite(3904, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground442.body.immovable = true;
	Ground442.body.allowRotation = false;
	Ground442.body.allowGravity = false;

	var Ground452 = this.game.add.tileSprite(3968, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground452.body.immovable = true;
	Ground452.body.allowRotation = false;
	Ground452.body.allowGravity = false;

	var Ground462 = this.game.add.tileSprite(4032, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground462.body.immovable = true;
	Ground462.body.allowRotation = false;
	Ground462.body.allowGravity = false;

	var Ground472 = this.game.add.tileSprite(4096, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground472.body.immovable = true;
	Ground472.body.allowRotation = false;
	Ground472.body.allowGravity = false;

	var Ground482 = this.game.add.tileSprite(4160, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground482.body.immovable = true;
	Ground482.body.allowRotation = false;
	Ground482.body.allowGravity = false;

	var Ground492 = this.game.add.tileSprite(4224, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground492.body.immovable = true;
	Ground492.body.allowRotation = false;
	Ground492.body.allowGravity = false;

	var Ground4113 = this.game.add.tileSprite(4352, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4113.body.immovable = true;
	Ground4113.body.allowRotation = false;
	Ground4113.body.allowGravity = false;

	var Ground4102 = this.game.add.tileSprite(4288, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4102.body.immovable = true;
	Ground4102.body.allowRotation = false;
	Ground4102.body.allowGravity = false;

	var Ground4122 = this.game.add.tileSprite(4416, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4122.body.immovable = true;
	Ground4122.body.allowRotation = false;
	Ground4122.body.allowGravity = false;

	var Ground4133 = this.game.add.tileSprite(4480, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4133.body.immovable = true;
	Ground4133.body.allowRotation = false;
	Ground4133.body.allowGravity = false;

	var Ground4143 = this.game.add.tileSprite(4544, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4143.body.immovable = true;
	Ground4143.body.allowRotation = false;
	Ground4143.body.allowGravity = false;

	var Ground4153 = this.game.add.tileSprite(4608, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4153.body.immovable = true;
	Ground4153.body.allowRotation = false;
	Ground4153.body.allowGravity = false;

	var Ground4163 = this.game.add.tileSprite(4672, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4163.body.immovable = true;
	Ground4163.body.allowRotation = false;
	Ground4163.body.allowGravity = false;

	var Ground4173 = this.game.add.tileSprite(4736, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4173.body.immovable = true;
	Ground4173.body.allowRotation = false;
	Ground4173.body.allowGravity = false;

	var Ground4183 = this.game.add.tileSprite(4800, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4183.body.immovable = true;
	Ground4183.body.allowRotation = false;
	Ground4183.body.allowGravity = false;

	var Ground4193 = this.game.add.tileSprite(4864, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground4193.body.immovable = true;
	Ground4193.body.allowRotation = false;
	Ground4193.body.allowGravity = false;

	var Ground41312 = this.game.add.tileSprite(4928, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41312.body.immovable = true;
	Ground41312.body.allowRotation = false;
	Ground41312.body.allowGravity = false;

	var Ground41412 = this.game.add.tileSprite(4992, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41412.body.immovable = true;
	Ground41412.body.allowRotation = false;
	Ground41412.body.allowGravity = false;

	var Ground41512 = this.game.add.tileSprite(5056, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41512.body.immovable = true;
	Ground41512.body.allowRotation = false;
	Ground41512.body.allowGravity = false;

	var Ground41612 = this.game.add.tileSprite(5120, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41612.body.immovable = true;
	Ground41612.body.allowRotation = false;
	Ground41612.body.allowGravity = false;

	var Ground41712 = this.game.add.tileSprite(5184, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41712.body.immovable = true;
	Ground41712.body.allowRotation = false;
	Ground41712.body.allowGravity = false;

	var Ground41812 = this.game.add.tileSprite(5248, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41812.body.immovable = true;
	Ground41812.body.allowRotation = false;
	Ground41812.body.allowGravity = false;

	var Ground41912 = this.game.add.tileSprite(5312, 768, 64, 64, 'Ground', 4, GroundBase);
	Ground41912.body.immovable = true;
	Ground41912.body.allowRotation = false;
	Ground41912.body.allowGravity = false;

	this.game.add.tileSprite(5568, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5632, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5696, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5760, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5824, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5888, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5952, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6016, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6080, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6144, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6208, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6272, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6336, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6400, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6464, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6528, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6592, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6656, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6720, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6784, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6848, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6912, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6976, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7040, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7104, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7168, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7232, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7296, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7360, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7424, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7488, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7552, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7616, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7680, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7744, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7808, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7872, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7936, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8000, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8064, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8128, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8192, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8256, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8320, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8384, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8448, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8512, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8576, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8640, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8704, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8768, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8832, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8896, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(8960, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(9024, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(9088, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(9152, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(9216, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(9280, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(9344, 768, 64, 64, 'snowwithgreytilesheet', 5, GroundBase);

	var Arrows = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var arrow = this.game.add.sprite(0, 896, 'arrow', null, Arrows);

	var Player = this.game.add.sprite(128, 576, 'urlsheetfixed', 0, prefabRoot_Scene1);
	Player.animations.add('swordWalk', [1, 2, 3, 2], 30, false);
	Player.animations.add('swordIdle', [0], 60, false);
	Player.animations.add('bowIdle', [6], 60, false);
	Player.animations.add('bowWalk', [7, 8, 9, 10], 30, false);
	Player.animations.add('swordAttack', [4, 5, 4], 30, false);
	this.game.physics.arcade.enable(Player);

	var Romans = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var russian1 = this.game.add.sprite(9024, 576, 'russian', 0, Romans);

	var russian = this.game.add.sprite(6720, 576, 'russian', 0, Romans);

	var roman = this.game.add.sprite(4992, 576, 'roman', 0, Romans);

	var Plat = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var ST004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	ST004.position.setTo(67008, 5376);

	var ST003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var ST002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var ST001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var ST000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL024 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL024.position.setTo(67008, 5376);

	var PL023 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL023.position.setTo(44672, 3584);

	var PL022 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL022.position.setTo(67008, 5376);

	var PL021 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL021.position.setTo(44672, 3584);

	var PL020 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL020.position.setTo(44672, 3584);

	var PL01F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01F.position.setTo(67008, 5376);

	var PL01E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01E.position.setTo(67008, 5376);

	var PL01D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01D.position.setTo(44672, 3584);

	var PL01C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01C.position.setTo(44672, 3584);

	var PL01B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01B.position.setTo(44672, 3584);

	var PL01A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01A.position.setTo(44672, 3584);

	var PL019 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL019.position.setTo(22336, 1792);

	var PL018 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL018.position.setTo(22336, 1792);

	var PL017 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL017.position.setTo(22336, 1792);

	var PL016 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL016.position.setTo(22336, 1792);

	var PL015 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL014 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL013 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL012 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL011 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB016 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB015 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB015.position.setTo(44672, 3584);

	var OB014 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB014.position.setTo(67008, 5376);

	var OB013 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB013.position.setTo(44672, 3584);

	var OB012 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB012.position.setTo(22336, 1792);

	var OB011 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB011.position.setTo(22336, 1792);

	var OB010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB010.position.setTo(44672, 3584);

	var OB00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB00F.position.setTo(22336, 1792);

	var OB00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB00E.position.setTo(22336, 1792);

	var OB00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB00D.position.setTo(44672, 3584);

	var OB00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(8128, 576, 64, 64, 'crate', null, OB003);

	this.game.add.tileSprite(8192, 576, 64, 64, 'crate', null, OB003);

	this.game.add.tileSprite(8128, 640, 64, 64, 'crate', null, OB003);

	this.game.add.tileSprite(8192, 640, 64, 64, 'crate', null, OB003);

	var OB002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(6144, 576, 64, 64, 'crate', null, OB002);

	this.game.add.tileSprite(6208, 576, 64, 64, 'crate', null, OB002);

	this.game.add.tileSprite(6144, 640, 64, 64, 'crate', null, OB002);

	this.game.add.tileSprite(6208, 640, 64, 64, 'crate', null, OB002);

	var OB001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(4288, 640, 64, 64, 'barrelupright', null, OB001);

	this.game.add.tileSprite(4352, 640, 64, 64, 'barrel', null, OB001);

	this.game.add.tileSprite(4416, 640, 64, 64, 'barrel', null, OB001);

	this.game.add.tileSprite(4480, 640, 64, 64, 'barrelupright', null, OB001);

	var OB000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(3712, 640, 64, 64, 'spritesheet', 1, OB000);

	this.game.add.tileSprite(3776, 640, 64, 64, 'spritesheet', 1, OB000);

	this.game.add.tileSprite(3776, 576, 64, 64, 'spritesheet', 1, OB000);

	this.game.add.tileSprite(3712, 576, 64, 64, 'spritesheet', 1, OB000);

	var GR00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(6848, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5568, 704, 64, 64, 'snowwithgreytilesheet', 0, GR002);

	this.game.add.tileSprite(6784, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(9344, 704, 64, 64, 'snowwithgreytilesheet', 2, GR002);

	this.game.add.tileSprite(8064, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8128, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6720, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6656, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6592, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5824, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5760, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5696, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5632, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6080, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6016, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5952, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(5888, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6336, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6272, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6208, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6144, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6528, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6464, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6400, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(9280, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(9216, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(9152, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(9088, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8320, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8256, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8192, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8576, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8512, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8448, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8384, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8832, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8768, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8704, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8640, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(9024, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8960, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8896, 704, 64, 64, 'snowwithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6912, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(6976, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7040, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7104, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7168, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7232, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7296, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7360, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7424, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7488, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7552, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7616, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7680, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7744, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7808, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7872, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(7936, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(8000, 704, 64, 64, 'icewithgreytilesheet', 1, GR002);

	var GR001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var CGR0001 = this.game.add.sprite(1920, 704, 'tiles', 'physics', GR001);
	CGR0001.scale.setTo(69.12, 2.56);

	this.game.add.tileSprite(3136, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3072, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3008, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2944, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2880, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2816, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2752, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2688, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2624, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2560, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2496, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2432, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2368, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2304, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2240, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2176, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2112, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(2048, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(1984, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(1920, 704, 64, 64, 'Ground', 0, GR001);

	this.game.add.tileSprite(3520, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3456, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3392, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3328, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3264, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3200, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(5312, 704, 64, 64, 'Ground', 2, GR001);

	this.game.add.tileSprite(4736, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4672, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4608, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4544, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4480, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4416, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4352, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4288, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4224, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4160, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4096, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4032, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3968, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3904, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3840, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3776, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3712, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3648, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(3584, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(5120, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(5056, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4992, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4928, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4864, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(4800, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(5248, 704, 64, 64, 'Ground', 1, GR001);

	this.game.add.tileSprite(5184, 704, 64, 64, 'Ground', 1, GR001);

	var GR000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(1216, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1152, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1088, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1024, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(960, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(896, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(832, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(768, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(704, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(640, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(576, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(512, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(448, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(384, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(320, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(256, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(192, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(128, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(64, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(0, 704, 64, 64, 'Ground', 0, GR000);

	this.game.add.tileSprite(1600, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1536, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1472, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1408, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1344, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1280, 704, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1664, 704, 64, 64, 'Ground', 2, GR000);

	var endScreen = this.game.add.group(prefabRoot_Scene1);

	var startScreen = this.game.add.group(prefabRoot_Scene1);

	var Prompts = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	this.game.add.tileSprite(8512, 192, 170, 64, 'swapweap', null, Prompts);

	this.game.add.tileSprite(512, 192, 170, 64, 'movement', null, Prompts);

	this.game.add.tileSprite(1664, 192, 128, 64, 'jump', null, Prompts);

	this.game.add.tileSprite(8704, 192, 128, 64, 'attack', null, Prompts);

	this.game.add.tileSprite(2304, 192, 128, 64, 'jump', null, Prompts);

	this.game.add.tileSprite(3648, 192, 128, 64, 'jump', null, Prompts);

	this.game.add.tileSprite(3008, 192, 128, 64, 'jump', null, Prompts);

	this.game.add.tileSprite(5760, 192, 170, 64, 'swapweap', null, Prompts);

	this.game.add.tileSprite(6656, 192, 128, 64, 'attack', null, Prompts);

	this.game.add.tileSprite(4928, 192, 128, 64, 'attack', null, Prompts);

	var theDress = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var firetilespritesheet13141 = this.game.add.sprite(9408, 768, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13141.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13151 = this.game.add.sprite(9472, 768, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13151.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13142 = this.game.add.sprite(9408, 704, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13142.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13152 = this.game.add.sprite(9472, 704, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13152.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13143 = this.game.add.sprite(9408, 640, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13143.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13153 = this.game.add.sprite(9472, 640, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13153.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13144 = this.game.add.sprite(9408, 576, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13144.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13154 = this.game.add.sprite(9472, 576, 'firetilespritesheet', 0, theDress);
	firetilespritesheet13154.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131411 = this.game.add.sprite(9408, 512, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131411.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131511 = this.game.add.sprite(9472, 512, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131511.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131421 = this.game.add.sprite(9408, 448, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131421.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131521 = this.game.add.sprite(9472, 448, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131521.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131431 = this.game.add.sprite(9408, 384, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131431.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131531 = this.game.add.sprite(9472, 384, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131531.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131441 = this.game.add.sprite(9408, 320, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131441.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131541 = this.game.add.sprite(9472, 320, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131541.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131412 = this.game.add.sprite(9408, 192, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131412.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131512 = this.game.add.sprite(9472, 192, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131512.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131422 = this.game.add.sprite(9408, 128, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131422.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131522 = this.game.add.sprite(9472, 128, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131522.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131432 = this.game.add.sprite(9408, 64, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131432.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131532 = this.game.add.sprite(9472, 64, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131532.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131442 = this.game.add.sprite(9408, 0, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131442.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131542 = this.game.add.sprite(9472, 0, 'firetilespritesheet', 0, theDress);
	firetilespritesheet131542.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet1314121 = this.game.add.sprite(9408, 256, 'firetilespritesheet', 0, theDress);
	firetilespritesheet1314121.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet1315121 = this.game.add.sprite(9472, 256, 'firetilespritesheet', 0, theDress);
	firetilespritesheet1315121.animations.add('Flame', [0, 1, 2, 3], 60, true);

	var MasterGroup = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	this.game.add.tileSprite(192, 1024, 64, 64, 'spikepng', null, MasterGroup);

	this.game.add.tileSprite(192, 1088, 64, 64, 'watersprite1', null, MasterGroup);

	this.game.add.tileSprite(192, 1152, 64, 64, 'watersprite2', null, MasterGroup);

	this.game.add.tileSprite(192, 1216, 64, 64, 'barrel', null, MasterGroup);

	this.game.add.tileSprite(192, 1280, 64, 64, 'barrelupright', null, MasterGroup);

	this.game.add.tileSprite(192, 1344, 64, 64, 'crate', null, MasterGroup);

	this.game.add.tileSprite(128, 1472, 64, 64, 'icespikepng', null, MasterGroup);

	this.game.add.tileSprite(128, 1408, 64, 64, 'icespikereverse', null, MasterGroup);

	this.game.add.tileSprite(256, 1152, 64, 64, 'oneblocksprite', null, MasterGroup);

	this.game.add.tileSprite(256, 1216, 64, 64, 'singleblockice', null, MasterGroup);

	this.game.add.tileSprite(256, 1280, 64, 64, 'singleblocksnow', null, MasterGroup);

	this.game.add.tileSprite(128, 1344, 64, 64, 'singleicespike', null, MasterGroup);

	this.game.add.tileSprite(256, 1344, 64, 64, 'singlesnow', null, MasterGroup);

	this.game.add.tileSprite(256, 1408, 64, 64, 'overhangsinglesprite', null, MasterGroup);

	this.game.add.tileSprite(256, 1024, 64, 64, 'singleblockiceoverhang', null, MasterGroup);

	this.game.add.tileSprite(256, 1088, 64, 64, 'singleblocksnowoverhang', null, MasterGroup);

	this.game.add.tileSprite(320, 1024, 64, 64, 'Ground', 0, MasterGroup);

	this.game.add.tileSprite(320, 1088, 64, 64, 'Ground', 1, MasterGroup);

	this.game.add.tileSprite(320, 1152, 64, 64, 'Ground', 2, MasterGroup);

	this.game.add.tileSprite(320, 1216, 64, 64, 'Ground', 3, MasterGroup);

	this.game.add.tileSprite(320, 1280, 64, 64, 'Ground', 4, MasterGroup);

	this.game.add.tileSprite(320, 1344, 64, 64, 'Ground', 5, MasterGroup);

	this.game.add.tileSprite(320, 1408, 64, 64, 'Ground', 6, MasterGroup);

	this.game.add.tileSprite(320, 1472, 64, 64, 'Ground', 7, MasterGroup);

	this.game.add.tileSprite(320, 1536, 64, 64, 'Ground', 8, MasterGroup);

	this.game.add.tileSprite(128, 1280, 64, 64, 'spritesheet', 1, MasterGroup);

	this.game.add.tileSprite(128, 1024, 64, 64, 'firetilespritesheet', 0, MasterGroup);

	this.game.add.tileSprite(128, 1088, 64, 64, 'firetilespritesheet', 1, MasterGroup);

	this.game.add.tileSprite(128, 1152, 64, 64, 'firetilespritesheet', 2, MasterGroup);

	this.game.add.tileSprite(128, 1216, 64, 64, 'firetilespritesheet', 3, MasterGroup);

	this.game.add.tileSprite(384, 1024, 64, 64, 'overhangsprite', 0, MasterGroup);

	this.game.add.tileSprite(384, 1088, 64, 64, 'overhangsprite', 1, MasterGroup);

	this.game.add.tileSprite(384, 1152, 64, 64, 'overhangsprite', 2, MasterGroup);

	this.game.add.tileSprite(448, 1024, 64, 64, 'urlsnowsprite', 0, MasterGroup);

	this.game.add.tileSprite(448, 1088, 64, 64, 'urlsnowsprite', 1, MasterGroup);

	this.game.add.tileSprite(448, 1152, 64, 64, 'urlsnowsprite', 2, MasterGroup);

	this.game.add.tileSprite(448, 1216, 64, 64, 'urlsnowsprite', 3, MasterGroup);

	this.game.add.tileSprite(448, 1280, 64, 64, 'urlsnowsprite', 4, MasterGroup);

	this.game.add.tileSprite(448, 1472, 64, 64, 'urlsnowsprite', 5, MasterGroup);

	this.game.add.tileSprite(448, 1344, 64, 64, 'urlsnowsprite', 6, MasterGroup);

	this.game.add.tileSprite(448, 1408, 64, 64, 'urlsnowsprite', 7, MasterGroup);

	this.game.add.tileSprite(448, 1536, 64, 64, 'urlsnowsprite', 8, MasterGroup);

	this.game.add.tileSprite(512, 1024, 64, 64, 'urlsnowsprite2', 0, MasterGroup);

	this.game.add.tileSprite(512, 1088, 64, 64, 'urlsnowsprite2', 1, MasterGroup);

	this.game.add.tileSprite(512, 1152, 64, 64, 'urlsnowsprite2', 2, MasterGroup);

	this.game.add.tileSprite(512, 1216, 64, 64, 'urlsnowsprite2', 3, MasterGroup);

	this.game.add.tileSprite(512, 1280, 64, 64, 'urlsnowsprite2', 4, MasterGroup);

	this.game.add.tileSprite(512, 1344, 64, 64, 'urlsnowsprite2', 5, MasterGroup);

	this.game.add.tileSprite(512, 1408, 64, 64, 'urlsnowsprite2', 6, MasterGroup);

	this.game.add.tileSprite(512, 1472, 64, 64, 'urlsnowsprite2', 7, MasterGroup);

	this.game.add.tileSprite(512, 1536, 64, 64, 'urlsnowsprite2', 8, MasterGroup);

	this.game.add.tileSprite(384, 1216, 64, 64, 'iceoverhang', 0, MasterGroup);

	this.game.add.tileSprite(384, 1280, 64, 64, 'iceoverhang', 1, MasterGroup);

	this.game.add.tileSprite(384, 1344, 64, 64, 'iceoverhang', 2, MasterGroup);

	this.game.add.tileSprite(384, 1408, 64, 64, 'snowoverhang', 0, MasterGroup);

	this.game.add.tileSprite(384, 1472, 64, 64, 'snowoverhang', 1, MasterGroup);

	this.game.add.tileSprite(384, 1536, 64, 64, 'snowoverhang', 2, MasterGroup);

	this.game.add.tileSprite(704, 1024, 64, 64, 'snowwithgrey', 0, MasterGroup);

	this.game.add.tileSprite(704, 1088, 64, 64, 'snowwithgrey', 1, MasterGroup);

	this.game.add.tileSprite(704, 1152, 64, 64, 'snowwithgrey', 2, MasterGroup);

	this.game.add.tileSprite(704, 1216, 64, 64, 'icewithgrey', 0, MasterGroup);

	this.game.add.tileSprite(704, 1280, 64, 64, 'icewithgrey', 1, MasterGroup);

	this.game.add.tileSprite(704, 1344, 64, 64, 'icewithgrey', 2, MasterGroup);

	this.game.add.tileSprite(576, 1024, 64, 64, 'icewithgreytilesheet', 0, MasterGroup);

	this.game.add.tileSprite(576, 1088, 64, 64, 'icewithgreytilesheet', 1, MasterGroup);

	this.game.add.tileSprite(576, 1152, 64, 64, 'icewithgreytilesheet', 2, MasterGroup);

	this.game.add.tileSprite(576, 1216, 64, 64, 'icewithgreytilesheet', 3, MasterGroup);

	this.game.add.tileSprite(576, 1280, 64, 64, 'icewithgreytilesheet', 4, MasterGroup);

	this.game.add.tileSprite(576, 1344, 64, 64, 'icewithgreytilesheet', 5, MasterGroup);

	this.game.add.tileSprite(576, 1408, 64, 64, 'icewithgreytilesheet', 6, MasterGroup);

	this.game.add.tileSprite(576, 1472, 64, 64, 'icewithgreytilesheet', 7, MasterGroup);

	this.game.add.tileSprite(576, 1536, 64, 64, 'icewithgreytilesheet', 8, MasterGroup);

	this.game.add.tileSprite(640, 1024, 64, 64, 'snowwithgreytilesheet', 0, MasterGroup);

	this.game.add.tileSprite(640, 1088, 64, 64, 'snowwithgreytilesheet', 1, MasterGroup);

	this.game.add.tileSprite(640, 1152, 64, 64, 'snowwithgreytilesheet', 2, MasterGroup);

	this.game.add.tileSprite(640, 1280, 64, 64, 'snowwithgreytilesheet', 3, MasterGroup);

	this.game.add.tileSprite(640, 1216, 64, 64, 'snowwithgreytilesheet', 4, MasterGroup);

	this.game.add.tileSprite(640, 1344, 64, 64, 'snowwithgreytilesheet', 5, MasterGroup);

	this.game.add.tileSprite(640, 1408, 64, 64, 'snowwithgreytilesheet', 6, MasterGroup);

	this.game.add.tileSprite(640, 1472, 64, 64, 'snowwithgreytilesheet', 7, MasterGroup);

	this.game.add.tileSprite(128, 1536, 64, 64, 'icespikepngleft', null, MasterGroup);

	this.game.add.tileSprite(192, 1472, 64, 64, 'icespikepngright', null, MasterGroup);

	this.game.add.tileSprite(192, 1536, 64, 64, 'icespikepngdown', null, MasterGroup);

	this.game.add.tileSprite(640, 1536, 64, 64, 'snowwithgreytilesheet', 8, MasterGroup);

	this.game.add.tileSprite(1088, 1088, 128, 64, 'attack', null, MasterGroup);

	this.game.add.tileSprite(1088, 1024, 128, 64, 'jump', null, MasterGroup);

	this.game.add.tileSprite(1088, 960, 170, 64, 'movement', null, MasterGroup);

	this.game.add.tileSprite(1088, 1152, 170, 64, 'swapweap', null, MasterGroup);

	 // public fields

	this.fCollisionLayer = CollisionLayer;
	this.fWater = Water;
	this.fW006 = W006;
	this.fW005 = W005;
	this.fW004 = W004;
	this.fW003 = W003;
	this.fW002 = W002;
	this.fW001 = W001;
	this.fW000 = W000;
	this.fHazards = Hazards;
	this.fFIREWALL = FIREWALL;
	this.fH010 = H010;
	this.fH00F = H00F;
	this.fH00E = H00E;
	this.fH00D = H00D;
	this.fH00C = H00C;
	this.fH00B = H00B;
	this.fH00A = H00A;
	this.fH009 = H009;
	this.fH008 = H008;
	this.fH007 = H007;
	this.fH006 = H006;
	this.fH005 = H005;
	this.fH004 = H004;
	this.fH003 = H003;
	this.fH002 = H002;
	this.fH001 = H001;
	this.fH000 = H000;
	this.fGroundBase = GroundBase;
	this.fArrows = Arrows;
	this.fArrow = arrow;
	this.fPlayer = Player;
	this.fRomans = Romans;
	this.fRussian1 = russian1;
	this.fRussian = russian;
	this.fRoman = roman;
	this.fPlat = Plat;
	this.fST004 = ST004;
	this.fST003 = ST003;
	this.fST002 = ST002;
	this.fST001 = ST001;
	this.fST000 = ST000;
	this.fPL024 = PL024;
	this.fPL023 = PL023;
	this.fPL022 = PL022;
	this.fPL021 = PL021;
	this.fPL020 = PL020;
	this.fPL01F = PL01F;
	this.fPL01E = PL01E;
	this.fPL01D = PL01D;
	this.fPL01C = PL01C;
	this.fPL01B = PL01B;
	this.fPL01A = PL01A;
	this.fPL019 = PL019;
	this.fPL018 = PL018;
	this.fPL017 = PL017;
	this.fPL016 = PL016;
	this.fPL015 = PL015;
	this.fPL014 = PL014;
	this.fPL013 = PL013;
	this.fPL012 = PL012;
	this.fPL011 = PL011;
	this.fPL010 = PL010;
	this.fPL00F = PL00F;
	this.fPL00E = PL00E;
	this.fPL00D = PL00D;
	this.fPL00C = PL00C;
	this.fPL00B = PL00B;
	this.fPL00A = PL00A;
	this.fPL009 = PL009;
	this.fPL008 = PL008;
	this.fPL007 = PL007;
	this.fPL006 = PL006;
	this.fPL005 = PL005;
	this.fPL004 = PL004;
	this.fPL003 = PL003;
	this.fPL002 = PL002;
	this.fPL001 = PL001;
	this.fPL000 = PL000;
	this.fOB016 = OB016;
	this.fOB015 = OB015;
	this.fOB014 = OB014;
	this.fOB013 = OB013;
	this.fOB012 = OB012;
	this.fOB011 = OB011;
	this.fOB010 = OB010;
	this.fOB00F = OB00F;
	this.fOB00E = OB00E;
	this.fOB00D = OB00D;
	this.fOB00C = OB00C;
	this.fOB00B = OB00B;
	this.fOB00A = OB00A;
	this.fOB009 = OB009;
	this.fOB008 = OB008;
	this.fOB007 = OB007;
	this.fOB006 = OB006;
	this.fOB005 = OB005;
	this.fOB004 = OB004;
	this.fOB003 = OB003;
	this.fOB002 = OB002;
	this.fOB001 = OB001;
	this.fOB000 = OB000;
	this.fGR00A = GR00A;
	this.fGR009 = GR009;
	this.fGR008 = GR008;
	this.fGR007 = GR007;
	this.fGR006 = GR006;
	this.fGR005 = GR005;
	this.fGR004 = GR004;
	this.fGR003 = GR003;
	this.fGR002 = GR002;
	this.fGR001 = GR001;
	this.fGR000 = GR000;
	this.fEndScreen = endScreen;
	this.fStartScreen = startScreen;
	this.fPrompts = Prompts;
	this.fTheDress = theDress;
	this.fMasterGroup = MasterGroup;

	/* --- post-init-begin --- */

	// you can insert code here

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var Scene3_proto = Object.create(Phaser.Group.prototype);
Scene3.prototype = Scene3_proto;
Scene3.prototype.constructor = Phaser.Group;

/* --- end generated code --- */
// -- user code here --
